title: Disruptive Advertising APS
description: Simulating an intelligent advertising algorithm with realtime inputs from search results and more
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman